### PR TITLE
Release v1.0.0

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Let's cut a v1

#### Ticket Link
Part of https://github.com/mattermost/mattermost-plugin-antivirus/issues/32

### CODE REVIEW

**Review by iomodo — APPROVED** [review]

**Review by mickmister — APPROVED** [review]

**Comment by hanzei** [comment]
@DHaussermann Would you be open cutting the release without further QA testing?

**Comment by DHaussermann** [comment]
@hanzei I have deployed the plugin and made sure it can start. 
Unfortunately for this one - There's not much testing I can do without a Clam AV setup. 

Where there any significant changes from the current release?
Is this a plugin we have enabled on community so it can be tested there?

We could maybe proceed with this release and I will work on formalizing the test process for this in the future.

**Comment by hanzei** [comment]
@DHaussermann The only significant change was added in https://github.com/mattermost/mattermost-plugin-antivirus/pull/31, but that PR wasn't tested. The plugin is not enabled on community.

**Comment by hanzei** [comment]
Not much has changed since the last release. Let's merge this as it is.

**Comment by hanzei** [comment]
CI is having issues: https://community.mattermost.com/core/pl/q3yrwa1peprymbnfzthsoxtxfy

**Pull request merged**
